// === Lobe Icons 完整图标列表 ===
// 通过 unpkg CDN 加载: https://unpkg.com/@lobehub/icons-static-svg@1.87.0/icons/{slug}.svg
// 数据源: @lobehub/icons-static-svg

/** 有 -color 彩色变体的图标 slug 集合，用于直接加载彩色版避免 404 回退延迟 */
export const COLOR_ICON_SLUGS: Set<string> = new Set([
  'adobe', 'adobefirefly', 'agentvoice', 'ai2', 'ai21-brand', 'ai302', 'ai360',
  'aihubmix', 'aimass', 'aionlabs', 'akashchat', 'alibaba', 'alibaba-brand',
  'alibabacloud', 'amp', 'antgroup', 'antgroup-brand', 'antigravity', 'anyscale',
  'apertis', 'arcee', 'askverdict', 'assemblyai', 'automatic', 'aws', 'aws-brand',
  'aya', 'azure', 'azureai', 'baichuan', 'baidu', 'baidu-brand', 'baiducloud',
  'bailian', 'bedrock', 'bilibili', 'bing', 'briaai', 'burncloud', 'bytedance',
  'bytedance-brand', 'centml', 'centml-brand', 'cerebras', 'cerebras-brand',
  'chatglm', 'cherrystudio', 'civitai', 'civitai-text', 'claude', 'claudecode',
  'cloudflare', 'codeflicker', 'codegeex', 'codex', 'cogvideo', 'cogview', 'cohere',
  'colab', 'cometapi', 'comfyui', 'commanda', 'copilot', 'copilotkit', 'coqui',
  'crewai', 'crewai-brand', 'crusoe', 'dalle', 'dbrx', 'dbrx-brand', 'deepcogito',
  'deepinfra', 'deepl', 'deepmind', 'deepseek', 'dify', 'doc2x', 'docsearch',
  'doubao', 'essentialai', 'exa', 'fal', 'fastgpt', 'featherless', 'figma',
  'fireworks', 'gemini', 'geminicli', 'gemma', 'glmv', 'google', 'google-brand',
  'googlecloud', 'googlecloud-brand', 'gradio', 'greptile', 'hailuo', 'higress',
  'huawei', 'huaweicloud', 'huggingface', 'hunyuan', 'hyperbolic', 'iflytekcloud',
  'infermatic', 'infinigence', 'internlm', 'jimeng', 'junie', 'kimi', 'kling',
  'kluster', 'kolors', 'kwaikat-text', 'kwaipilot', 'langchain', 'langfuse',
  'langgraph', 'langsmith', 'leptonai', 'lg', 'livekit', 'llamaindex', 'llava',
  'llmapi', 'lobehub', 'longcat', 'lovable', 'luma', 'make', 'mcpso', 'menlo',
  'meshy', 'meta', 'meta-brand', 'metaai', 'microsoft', 'minimax', 'mistral',
  'modelscope', 'monica', 'morph', 'myshell', 'n8n', 'nanobanana', 'newapi',
  'nova', 'novita', 'nplcloud', 'nvidia', 'obsidian', 'openchat', 'openclaw',
  'openhands', 'palm', 'perplexity', 'phidata', 'pixverse', 'player2', 'poe',
  'ppio', 'prunaai', 'pydanticai', 'qingyan', 'qiniu', 'qoder', 'qwen', 'replit',
  'rsshub', 'rwkv', 'sambanova', 'search1api', 'sensenova', 'sensenova-brand',
  'siliconcloud', 'skywork', 'smithery', 'snowflake', 'sophnet', 'sora', 'spark',
  'speedai', 'stability', 'stability-brand', 'statecloud', 'stepfun', 'straico',
  'streamlake', 'submodel', 'targon', 'tavily', 'tencent', 'tencent-brand',
  'tencentcloud', 'tiangong', 'tii', 'together', 'together-brand', 'trae', 'tripo',
  'udio', 'unstructured', 'upstage', 'venice', 'vertexai', 'vidu', 'vllm',
  'volcengine', 'voyage', 'wenxin', 'workersai', 'xinference', 'xpay', 'xuanyuan',
  'yi', 'yuanbao', 'zapier', 'zeabur', 'zencoder', 'zhipu',
])

/** 所有可用图标的 slug（按类目分组） */
export const SOURCE_ICON_CATEGORIES: { label: string; icons: string[] }[] = [
  {
    label: '大模型',
    icons: [
      'claude', 'deepseek', 'openai', 'gemini', 'qwen', 'doubao',
      'mistral', 'grok', 'hunyuan', 'spark', 'baichuan', 'chatglm',
      'stepfun', 'moonshot', 'kimi', 'minimax', 'cohere',
      'wenxin', 'yi', 'sensenova', 'commanda', 'dbrx', 'phind',
      'perplexity', 'elevenlabs', 'stability', 'flux',
      'nvidia', 'nova', 'palm', 'gemma',
      'cogvideo', 'cogview', 'sora', 'dalle', 'liquid',
      'rwkv', 'skywork', 'voyage', 'deepcogito', 'longcat',
      'llava', 'glmv', 'morph', 'openchat', 'codegeex',
      'geminicli', 'nanobanana', 'kolors', 'reve', 'relace',
      'inception', 'magic', 'prunaai', 'meshy', 'kwaikat',
      'kwaipilot', 'submodel', 'fishaudio', 'dolphin',
      'llmapi', 'command', 'sophnet',
    ],
  },
  {
    label: '国内模型',
    icons: [
      'qwen', 'doubao', 'hunyuan', 'spark', 'baichuan', 'chatglm',
      'kimi', 'moonshot', 'yi', 'wenxin', 'minimax', 'stepfun',
      'sensenova', 'skywork', 'deepseek', 'codegeex',
      'cogvideo', 'cogview', 'bilibiliindex', 'glmv',
      'kolors', 'kwaikat', 'kwaipilot', 'xiaomimimo', 'xuanyuan',
      'rwkv', 'longcat', 'internlm', 'infinigence',
      'fishaudio', 'sophnet',
    ],
  },
  {
    label: '提供商',
    icons: [
      'anthropic', 'openai', 'google', 'meta', 'microsoft',
      'alibaba', 'baidu', 'bytedance', 'tencent', 'zhipu',
      'alibabacloud', 'baiducloud', 'tencentcloud', 'huaweicloud', 'volcengine',
      'aws', 'azure', 'azureai', 'cloudflare', 'vercel',
      'deepinfra', 'together', 'fireworks', 'groq', 'nebius',
      'cerebras', 'replicate', 'sambanova', 'upstage',
      'jina', 'novita', 'ppio', 'targon',
      'modelscope', 'siliconcloud', 'xinference', 'ollama', 'vllm',
      'deepmind', 'vertexai', 'ai21', 'cohere', 'arcee',
      'baseten', 'centml', 'crusoe', 'fal', 'featherless',
      'friendli', 'huggingface', 'hyperbolic', 'kluster', 'lambda',
      'leptonai', 'nplcloud', 'parasail', 'snowflake', 'speedai',
      'straico', 'statecloud', 'tii', 'workersai', 'lmstudio',
      'bailian', 'giteeai', 'newapi', 'search1api', 'searchapi',
      'openrouter', 'lmstudio',
    ],
  },
  {
    label: '工具',
    icons: [
      'claudecode', 'cursor', 'opencode', 'codex', 'copilot',
      'windsurf', 'v0', 'lovable', 'replit', 'cline', 'roocode',
      'codeflicker', 'trae', 'junie', 'kilocode', 'qoder',
      'comfyui', 'langchain', 'llamaindex', 'gradio', 'dify',
      'fastgpt', 'coze', 'deepai', 'glif', 'make', 'zapier',
      'githubcopilot', 'openwebui', 'lobehub', 'cherrystudio',
      'goose', 'openhands', 'openclaw', 'hermesagent',
      'n8n', 'smithery', 'phidata', 'mastra', 'crewai',
      'langfuse', 'langgraph', 'langsmith', 'metagpt', 'pydanticai',
      'livekit', 'colab', 'railway', 'zeabur', 'zencoder',
      'greptile', 'monica', 'doc2x', 'docsearch', 'rsshub',
      'aistudio', 'flowith', 'youmind', 'glama', 'novelai',
      'mcp', 'mcpso',
    ],
  },
  {
    label: '创意与媒体',
    icons: [
      'midjourney', 'dalle', 'sora', 'flux', 'stability',
      'runway', 'luma', 'kling', 'pika', 'viggle',
      'capcut', 'jimeng', 'hailuo', 'vidu', 'dreammachine',
      'haiper', 'tripo', 'vectorizerai', 'clipdrop', 'ideogram',
      'krea', 'lovart', 'meshy', 'pixverse', 'recraft',
      'topazlabs', 'udio', 'sunu', 'flora', 'lightricks',
      'figma', 'hedra', 'sync',
    ],
  },
  {
    label: '国际模型',
    icons: [
      'claude', 'gemini', 'gemma', 'palm', 'openai',
      'mistral', 'cohere', 'commanda', 'grok', 'llava',
      'dbrx', 'phind', 'perplexity', 'elevenlabs', 'stability',
      'flux', 'nvidia', 'nova', 'liquid', 'voyage',
      'aya', 'deepl', 'assemblyai', 'deepcogito', 'inception',
      'cogvideo', 'cogview',
    ],
  },
  {
    label: '品牌与平台',
    icons: [
      'adobe', 'apple', 'alibaba', 'tencent', 'baidu',
      'bytedance', 'huawei', 'google', 'microsoft', 'meta',
      'aws', 'cloudflare', 'vercel', 'github', 'notion',
      'bilibili', 'replicate', 'huggingface', 'figma', 'obsidian',
      'bing', 'yandex', 'ibm', 'nvidia', 'intel',
    ],
  },
  {
    label: '所有图标',
    icons: [
      'ace', 'adobe', 'adobefirefly', 'agentvoice', 'agui', 'ai2', 'ai21',
      'ai302', 'ai360', 'aihubmix', 'aimass', 'aionlabs', 'aistudio',
      'akashchat', 'alephalpha', 'alibaba', 'alibabacloud', 'amp', 'antgroup',
      'anthropic', 'antigravity', 'anyscale', 'apertis', 'apple', 'arcee',
      'askverdict', 'assemblyai', 'atlascloud', 'automatic', 'aws',
      'aya', 'azure', 'azureai', 'baai', 'baichuan', 'baidu', 'baiducloud',
      'bailian', 'baseten', 'bedrock', 'bfl', 'bilibili', 'bilibiliindex',
      'bing', 'briaai', 'burncloud', 'bytedance', 'capcut', 'centml',
      'cerebras', 'chatglm', 'cherrystudio', 'civitai', 'claude', 'claudecode',
      'cline', 'clipdrop', 'cloudflare', 'codeflicker', 'codegeex', 'codex',
      'cogvideo', 'cogview', 'cohere', 'colab', 'cometapi', 'comfyui',
      'commanda', 'copilot', 'copilotkit', 'coqui', 'coze', 'crewai', 'crusoe',
      'cursor', 'cybercut', 'dalle', 'dbrx', 'deepai', 'deepcogito', 'deepinfra',
      'deepl', 'deepmind', 'deepseek', 'dify', 'doc2x', 'docsearch', 'dolphin',
      'doubao', 'dreammachine', 'elevenlabs', 'elevenx', 'essentialai', 'exa',
      'fal', 'fastgpt', 'featherless', 'figma', 'fireworks', 'fishaudio', 'flora',
      'flowith', 'flux', 'friendli', 'gemini', 'geminicli', 'gemma', 'giteeai',
      'github', 'githubcopilot', 'glama', 'glif', 'glmv', 'google', 'googlecloud',
      'goose', 'gradio', 'greptile', 'grok', 'groq', 'hailuo', 'haiper', 'hedra',
      'hermesagent', 'higress', 'huawei', 'huaweicloud', 'huggingface', 'hunyuan',
      'hyperbolic', 'ibm', 'ideogram', 'iflytekcloud', 'inception', 'inference',
      'infermatic', 'infinigence', 'inflection', 'internlm', 'jimeng', 'jina',
      'junie', 'kilocode', 'kimi', 'kling', 'kluster', 'kolors', 'krea',
      'kwaikat', 'kwaipilot', 'lambda', 'langchain', 'langfuse', 'langgraph',
      'langsmith', 'leptonai', 'lg', 'lightricks', 'liquid', 'livekit',
      'llamaindex', 'llava', 'llmapi', 'lmstudio', 'lobehub', 'longcat',
      'lovable', 'lovart', 'luma', 'magic', 'make', 'manus', 'mastra', 'mcp',
      'mcpso', 'menlo', 'meshy', 'meta', 'metaai', 'metagpt', 'microsoft',
      'midjourney', 'minimax', 'mistral', 'modelscope', 'monica', 'moonshot',
      'morph', 'myshell', 'n8n', 'nanobanana', 'nebius', 'newapi', 'notebooklm',
      'notion', 'nousresearch', 'nova', 'novelai', 'novita', 'nplcloud', 'nvidia',
      'obsidian', 'ollama', 'openai', 'openchat', 'openclaw', 'opencode',
      'openhands', 'openrouter', 'openwebui', 'palm', 'parasail', 'perplexity',
      'phidata', 'phind', 'pika', 'pixverse', 'player2', 'poe', 'pollinations',
      'ppio', 'prunaai', 'pydanticai', 'qingyan', 'qiniu', 'qoder', 'qwen',
      'railway', 'recraft', 'relace', 'replicate', 'replit', 'reve', 'roocode',
      'rsshub', 'runway', 'rwkv', 'sambanova', 'search1api', 'searchapi',
      'sensenova', 'siliconcloud', 'skywork', 'smithery', 'snowflake', 'sophnet',
      'sora', 'spark', 'speedai', 'stability', 'statecloud', 'stepfun', 'straico',
      'streamlake', 'submodel', 'suno', 'sync', 'targon', 'tavily', 'tencent',
      'tencentcloud', 'tiangong', 'tii', 'together', 'topazlabs', 'trae', 'tripo',
      'turix', 'udio', 'unstructured', 'upstage', 'v0', 'vectorizerai', 'venice',
      'vercel', 'vertexai', 'vidu', 'viggle', 'vllm', 'volcengine', 'voyage',
      'wenxin', 'windsurf', 'workersai', 'xai', 'xiaomimimo', 'xinference',
      'xpay', 'xuanyuan', 'yandex', 'yi', 'youmind', 'yuanbao', 'zai', 'zapier',
      'zeabur', 'zencoder', 'zenmux', 'zeroone', 'zhipu',
    ],
  },
]

/** 所有图标的扁平去重列表（搜索用） */
export const SOURCE_ICONS_FLAT: string[] = [...new Set(SOURCE_ICON_CATEGORIES.flatMap(c => c.icons))].sort()

/** 工具默认 lobe 图标 slug */
export const TOOL_LOBE_ICONS: Record<string, string> = {
  claude_code: 'claudecode',
  codex: 'codex',
  cursor: 'cursor',
  opencode: 'opencode',
}
